// pages/cv.vue
<template>
  <!-- eslint-disable vue/no-v-html -->
  <v-row justify="center" align="center">
    <v-col cols="12">
      <v-row no-gutters align="center" justify="center">
        <h4 class="text-h4 primary--text" v-html="$t('page.cv.title')" />
        <v-spacer />
        <v-btn
          class="background--text"
          color="primary"
          href="/files/AlvaroBreyVilas-cv-20210118.pdf"
          download
          target="_blank"
        >
          <v-icon left>mdi-file-pdf</v-icon>
          <span>PDF version</span>
        </v-btn>
      </v-row>
      <CVItemsFilter v-model="itemFilter" />
      <v-timeline :dense="$nuxt.$vuetify.breakpoint.mdAndDown">
        <CVTimelineItemDisplay
          v-for="(item, index) in sortedItems"
          :key="item.key"
          :item="item"
          :is-left="index % 2 === 1"
        />
      </v-timeline>
    </v-col>
  </v-row>
</template>

<script lang="ts">
import Vue from 'vue'
import moment from 'moment'
import { CVTimelineItems } from '~/data/CVData'
import CVTimelineItemDisplay from '~/components/cv/CVTimelineItemDisplay.vue'
import { CVItemType, CVTimelineItem } from '~/model/CVModel'
import { Optional } from '~/types/utilityTypes'
import CVItemsFilter from '~/components/cv/CVItemsFilter.vue'

function getCompareDate(item: CVTimelineItem): Optional<moment.Moment> {
  return item.startDate ?? item.endDate
}

function sortTimelineItems(a: CVTimelineItem, b: CVTimelineItem): number {
  const aDate = getCompareDate(a)
  const bDate = getCompareDate(b)
  if (aDate === undefined) {
    return -1
  }
  if (bDate === undefined) {
    return 1
  }
  return bDate.unix() - aDate.unix()
}

export default Vue.extend({
  components: { CVItemsFilter, CVTimelineItemDisplay },
  data() {
    return {
      reverseOrder: false,
      itemFilter: undefined as Optional<CVItemType>
    }
  },
  computed: {
    sortedItems(): CVTimelineItem[] {
      let items = CVTimelineItems.sort(sortTimelineItems)
      if (this.itemFilter) {
        items = items.filter((item) => item.type === this.itemFilter)
      }
      if (this.reverseOrder) {
        items = items.reverse()
      }
      return items
    }
  },
  head() {
    return {
      title: this.$tc('nav.cv')
    }
  }
})
</script>

// src/routes/cv/+page.svelte
<script lang="ts">
  import { mdiFilePdfBox } from '@mdi/js'
  import CVItemsFilter from '$lib/components/cv/CVItemsFilter.svelte'
  import CVTimeline from '$lib/components/cv/CVTimeline.svelte'
  import SeoHead from '$lib/components/SeoHead.svelte'
  import Icon from '$lib/components/ui/Icon.svelte'
  import { CVTimelineItems } from '$lib/data/CVData'
  import { CV_PDF_FILENAME } from '$lib/generated/cvPdf'
  import { t } from '$lib/i18n'
  import { CVItemType } from '$lib/model/CVModel'
  import type { Optional } from '$lib/types/utilityTypes'
  import { sortTimelineItems } from '$lib/utils/cvTimeline'

  let filter = $state<Optional<CVItemType>>(undefined)

  const pdfHref = `/files/${CV_PDF_FILENAME}`

  const sortedItems = $derived(
    [...CVTimelineItems]
      .sort(sortTimelineItems)
      .filter((item) => item.type !== CVItemType.COURSE)
      .filter((item) => filter === undefined || item.type === filter)
  )
</script>

<SeoHead title={t('nav.cv')} />

<div class="mx-auto w-full sm:w-10/12 lg:w-8/12">
  <div class="mb-6 flex flex-wrap items-center justify-between gap-4">
    <!-- eslint-disable-next-line svelte/no-at-html-tags -- locale content, not user input -->
    <h1 class="text-4xl text-primary">{@html t('page.cv.title')}</h1>
    <a
      href={pdfHref}
      target="_blank"
      class="inline-flex items-center gap-2 rounded bg-primary px-4 py-2 text-sm font-medium text-on-primary uppercase hover:opacity-90"
    >
      <Icon path={mdiFilePdfBox} size={20} />
      PDF version
    </a>
  </div>

  <div class="mb-8">
    <CVItemsFilter bind:value={filter} />
  </div>

  <CVTimeline items={sortedItems} />
</div>
