// src/routes/about/+page.svelte
<script lang="ts">
  import BasicPage from '$lib/components/BasicPage.svelte'
  import SeoHead from '$lib/components/SeoHead.svelte'
  import { t } from '$lib/i18n'
</script>

<SeoHead title={t('nav.about')} />

<!-- eslint-disable svelte/no-at-html-tags -- locale content, not user input -->
<BasicPage title={t('page.about.title')}>
  <p class="mt-2">{@html t('page.about.paragraph1')}</p>
  <p class="mt-3">{@html t('page.about.paragraph2')}</p>
</BasicPage>

// pages/about.vue
<template>
  <!-- eslint-disable vue/no-v-html -->
  <BasicPage :title="$t('page.about.title')">
    <p class="text-body-1 mt-2" v-html="$t('page.about.paragraph1')" />
    <p class="text-body-1 mt-3" v-html="$t('page.about.paragraph2')" />
  </BasicPage>
</template>

<script lang="ts">
import Vue from 'vue'
import BasicPage from '~/components/BasicPage.vue'

export default Vue.extend({
  components: { BasicPage },
  head() {
    return {
      title: this.$tc('nav.about')
    }
  }
})
</script>
