// src/routes/contact/+page.svelte
<script lang="ts">
  import { mdiEmail, mdiGithub, mdiLinkedin } from '@mdi/js'
  import BasicPage from '$lib/components/BasicPage.svelte'
  import SeoHead from '$lib/components/SeoHead.svelte'
  import ContactItem from '$lib/components/contact/ContactItem.svelte'
  import { t } from '$lib/i18n'
  import { contactLinks } from '$lib/data/ContactData'

  const icons: Record<string, string> = {
    linkedIn: mdiLinkedin,
    gitHub: mdiGithub,
    mail: mdiEmail
  }

  const items = contactLinks.map((it) => ({ ...it, icon: icons[it.key] }))
</script>

<SeoHead title={t('nav.contact')} />

<BasicPage title={t('page.contact.title')}>
  <div
    class="mt-6 flex flex-col items-center gap-8 sm:flex-row sm:flex-wrap sm:justify-center sm:gap-x-20"
  >
    {#each items as item (item.key)}
      <ContactItem
        icon={item.icon}
        translationKey={item.key}
        link={item.link}
      />
    {/each}
  </div>
</BasicPage>

// pages/contact.vue
<template>
  <BasicPage :title="$t('page.contact.title')">
    <v-row justify="center" align="center" class="mt-6">
      <ContactItemDisplay
        v-for="item in items"
        :key="item.key"
        :translation-key="item.key"
        :link="item.link"
        :icon="item.icon"
      />
    </v-row>
  </BasicPage>
</template>

<script lang="ts">
import Vue from 'vue'
import { mdiEmail, mdiGithub, mdiLinkedin } from '@mdi/js'
import BasicPage from '~/components/BasicPage.vue'
import ContactItemDisplay from '~/components/contact/ContactItemDisplay.vue'
import { contactLinks } from '~/data/ContactData'

const icons: Record<string, string> = {
  linkedIn: mdiLinkedin,
  gitHub: mdiGithub,
  mail: mdiEmail
}

const items = contactLinks.map((it) => ({ ...it, icon: icons[it.key] }))

export default Vue.extend({
  components: { ContactItemDisplay, BasicPage },
  data() {
    return {
      items
    }
  },
  head() {
    return {
      title: this.$tc('nav.contact')
    }
  }
})
</script>
