// src/lib/components/cv/CVItemsFilter.svelte
<script lang="ts">
  import { mdiCheck } from '@mdi/js'
  import { CVItemType } from '../../model/CVModel'
  import { CVItemTypeColors } from '../../model/CVUIModel'
  import type { Optional } from '../../types/utilityTypes'
  import { t } from '../../i18n'
  import Icon from '../ui/Icon.svelte'

  interface Props {
    value?: Optional<CVItemType>
  }

  let { value = $bindable(undefined) }: Props = $props()

  const types = Object.values(CVItemType).filter(
    (type) => type !== CVItemType.COURSE
  )
</script>

<div class="flex flex-wrap gap-2">
  <button
    type="button"
    onclick={() => (value = undefined)}
    class="flex items-center gap-1 rounded-full border px-3 py-1 text-sm transition-colors {value ===
    undefined
      ? 'border-body bg-body text-background'
      : 'border-muted/40 text-body'}"
  >
    {#if value === undefined}<Icon path={mdiCheck} size={16} />{/if}
    {t('global.filter.all')}
  </button>
  {#each types as type (type)}
    <button
      type="button"
      onclick={() => (value = type)}
      style="border-color: {CVItemTypeColors[
        type
      ]}; background-color: {value === type
        ? CVItemTypeColors[type]
        : 'transparent'}; color: {value === type
        ? 'white'
        : CVItemTypeColors[type]}"
      class="flex items-center gap-1 rounded-full border px-3 py-1 text-sm transition-colors"
    >
      {#if value === type}<Icon path={mdiCheck} size={16} />{/if}
      {t(`page.cv.filter.${type}`)}
    </button>
  {/each}
</div>

// components/cv/CVItemsFilter.vue
<template>
  <v-chip-group v-model="selection" column mandatory>
    <v-chip filter>
      {{ $t('global.filter.all') }}
    </v-chip>
    <v-chip
      v-for="type in typesAndColors"
      :key="type.type"
      text-color="white"
      filter
      :color="type.colorClass"
    >
      {{ $t(`page.cv.filter.${type.type}`) }}
    </v-chip>
  </v-chip-group>
</template>

<script lang="ts">
import Vue, { PropOptions } from 'vue'
import { CVItemType } from '~/model/CVModel'
import { Optional } from '~/types/utilityTypes'
import { CVItemTypeColors } from '~/model/ui/CVUIModel'

interface TypeAndColor {
  type: CVItemType
  colorClass: string
}

export default Vue.extend({
  name: 'CVItemsFilter',
  props: {
    value: {
      type: String,
      default: undefined
    } as PropOptions<Optional<CVItemType>>
  },
  data() {
    return {
      selection: 0
    }
  },
  computed: {
    typesAndColors(): TypeAndColor[] {
      return Object.values(CVItemType)
        .filter((type) => type !== CVItemType.COURSE)
        .map((type) => ({
          type,
          colorClass: CVItemTypeColors[type]
        }))
    }
  },
  watch: {
    value: {
      immediate: true,
      handler(val: Optional<CVItemType>) {
        if (val === undefined) {
          this.selection = 0
        } else {
          const typeIndex = this.typesAndColors.findIndex(
            (type) => type.type === val
          )
          this.selection = typeIndex + 1
        }
      }
    },
    selection(val: number) {
      if (val === 0) {
        this.$emit('input', undefined)
      } else {
        const type = this.typesAndColors[val - 1].type
        this.$emit('input', type)
      }
    }
  }
})
</script>
